training_folder: 
    j100: "/j100"
    2016MU: "/2016MU/10134000"
model_defaults: 
    #efficiency: ["j100","2016MU"]
    acceptance: ["j100"]
model_variants:
    efficiency:
        j100: ["v1","v2"]
        #2016MU: ["v1","v2"]
    #acceptance:
        #j100: ["v1","v2"]
        #2016MU: ["v1","v2"]